# Generated by Django 3.1.1 on 2020-12-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, error_messages={'unique': 'this mobile number is already exist'}, null=True, unique=True, verbose_name='User Phone'),
        ),
    ]
